CREATE ROLE bookstore WITH LOGIN PASSWORD 'bookstore';

CREATE ROLE book WITH LOGIN PASSWORD 'book' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE books_database;
GRANT ALL PRIVILEGES ON DATABASE books_database TO book ;
GRANT ALL PRIVILEGES ON DATABASE books_database TO bookstore;

CREATE ROLE inventory WITH LOGIN PASSWORD 'inventory' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE inventory_database;
GRANT ALL PRIVILEGES ON DATABASE inventory_database TO inventory;
GRANT ALL PRIVILEGES ON DATABASE inventory_database TO bookstore;
