version: "3"
# tag::adocSnippet[]
services:
  ui-vintagestore:
    image: "agoncal/ui-vintagestore:2.0.0-SNAPSHOT"
    container_name: "vintage_store_ui"
    ports:
      - "8700:8700"
    depends_on:
      - rest-number
      - rest-book
  rest-number:
    image: "agoncal/rest-number:2.0.0-SNAPSHOT"
    container_name: "vintage_store_rest_number"
    ports:
      - "8701:8701"
  rest-book:
    image: "agoncal/rest-book:2.0.0-SNAPSHOT"
    container_name: "vintage_store_rest_book"
    ports:
      - "8702:8702"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/books_database
      - ORG_AGONCAL_FASCICLE_QUARKUS_BOOK_CLIENT_NUMBERPROXY_MP_REST_URL=http://rest-number:8701
  database:
    image: "postgres:14.1"
    container_name: "vintage_store_books_database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=books_database
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=book
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  monitoring:
    image: "prom/prometheus:v2.31.1"
    container_name: "vintage_store_monitoring"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
# end::adocSnippet[]
